- hosts: jenkins
  become: true
 
 
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install net-tools 
      apt:
        name: net-tools
        update_cache: yes

    - name: Install Java 
      apt:
        name: openjdk-8-jdk
        update_cache: yes

    - name: "install git"
      apt:
        name: git
        state: present

    - name: "install wget"
      apt:
        name: wget
        state: present

    - name: download jenkins.repo
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/

    - name: Import jenkins key
      apt_key:
        file: /usr/jenkins.io.key
        state: present

    - name: Add Jenkins package
      shell: echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list
      

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: "install jenkins"
      apt:
        name: jenkins
        state: present

    - name: init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: print init password jenkins
      debug:
        var: result.stdout